### ISSUE TITLE
"duplicate key error index:"

### ISSUE THREAD

**Issue by ChrisJGayle** [yubozhao/meteor-link-accounts#10]
In the event that a user; 
1. uses Facebook to create an account automatically
2. logs out
3. creates a new account manually
4. attempts to link the account in #3 with the same Facebook user used to create an account in #1

- produces a "Exception while invoking method 'login' MongoError: E11000 duplicate key error index:" error, any suggestions/solutions?

**Comment by yubozhao** [comment]
hi @ChrisJGayle did you solve this issue??

**Comment by yubozhao** [comment]
@ChrisJGayle  Let me know if this is solved, I am going to close it for now
