### ISSUE TITLE
unlink accounts

### ISSUE THREAD

**Issue by bianchimro** [yubozhao/meteor-link-accounts#11]
It would be nice to have an API to remove linked accounts from the meteor db,
something like:

    Meteor.unlinkFacebook()
    Meteor.unlinkTwitter()

etc.

**Comment by yubozhao** [comment]
yeah. that sounds like a good feature to have.  

I left it out initially because all of the complexity could be involved. it might be up to application developer to decided what impact it could has on their app.

**Comment by yubozhao** [comment]
To remove it is pretty easy. But I don't know how big the impact it could has.

**Comment by bianchimro** [comment]
I think it would be nice just to provide an API that developer can call in his app.
This will have an impact on current application state, but I'd leave it to the developer.
Probably safest thing thing to do after this kind of action would be logging out user and asking to login again, but it depends on how each application is structured.

**Comment by yubozhao** [comment]
@bianchimro 

That sounds like something reasonable.  I will work on it for the next release

**Comment by bianchimro** [comment]
sounds great,
thanks!

Il martedì 17 febbraio 2015, Bozhao <notifications@github.com> ha scritto:

> @bianchimro <https://github.com/bianchimro>
>
> That sounds like something reasonable. I will work on it for the next
> release
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yubozhao/meteor-link-accounts/issues/11#issuecomment-74739309>
> .
>


-- 
Mauro Bianchi
bianchimro@gmail.com
www.inmagik.com

**Comment by zhaoyao91** [comment]
+10086!!!
强势期待这个功能！！！

**Comment by yubozhao** [comment]
078e3709c3c3010a357a0b960a4139e3b0ed0fcd   Let me know how this commit goes

**Comment by jfraboni** [comment]
Hi, what's the API for unlinking an account?

**Comment by yubozhao** [comment]
@jfraboni 
You can check out this commit.

You can either call Accounts.unlinkService  or a meteor method '_accounts/unlink/service'
