### ISSUE TITLE
No error thrown when a social account is already in use

### ISSUE THREAD

**Issue by Juaanma** [yubozhao/meteor-link-accounts#14]
The package does not return an error when we try to link a social account that has been already used in another user. Instead, we receive a server-side exception: "Exception while invoking method 'login' MongoError: E11000 duplicate key error index".
It would be great if a Meteor.error is returned, so that it can be displayed in the client side of the site.

**Comment by yubozhao** [comment]
@Juaanma 

Thank you for the bug, I will update it in the next release

**Comment by yubozhao** [comment]
check out ef05988c5fcbc737f16580b8eb015f284272d51f

**Comment by yubozhao** [comment]
Going to close the issue now. Feel free to reopen it.
