### ISSUE TITLE
how can I use accounts-facebook + cordova-fb for mobile purposes?

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [yubozhao/meteor-link-accounts#15]
Hi, I have an app 99folks.com which uses https://atmospherejs.com/particle4dev/cordova-fb to make facebook signin in cordova apps, I'd like to use the `link-accounts` to provide a screen to user remove or readd your facebook id, but I can't do it because the cordova-fb use as dependencies the `accounts-facebook` and the `link-accounts` (for facebook) don't work without `accounts-facebook` installed.
When I try to install `accounts-facebook` as duplicated dependency, it throws the error:

``` bash
Error: Duplicate service: facebook
W20150608-16:49:53.107(-3)? (STDERR)   at Object.Accounts.oauth.registerService (/Users/caio/Documents/workspace/99folks/app-99folks/.meteor/local/build/programs/server/packages/accounts-oauth.js:32:11)
```

Is there a way to reuse the `accounts-facebook` from `cordova-fb` or just ignore the warning and use both `accounts-facebook`?

**Comment by lorensr** [comment]
I tried commenting out the error throwing in https://github.com/yubozhao/meteor-link-accounts/blob/6108a1d706e175ab1555981d52995272a39be5fd/facebook.js
but at least with pkg I'm using, `vicentealencar:cordova-fb`, a new account is created and logged in. 

$100 bounty to whoever fixes this 🙏😄

**Comment by lorensr** [comment]
Works with this package: https://github.com/splendido/meteor-accounts-meld

**Comment by yubozhao** [comment]
Sorry for been away for a while.  @caio-ribeiro-pereira @lorensr 

Ohhh, once Meteor 1.2 comes out, I will fix it during the building step.

**Comment by yubozhao** [comment]
This has update in package version 1.1.7.  Going to close this for now, and if any issue feel free to reopen it.

**Comment by Sntax** [comment]
I am still a little unclear on how to approach this, how exactly do you link accounts on cordova and web without running into duplicate service errors?
