### ISSUE TITLE
Additional account being created instead of being linked - any thoughts

### ISSUE THREAD

**Issue by phinmpofu** [yubozhao/meteor-link-accounts#18]
I'm attempting to use this package. The README file gave me an indication that it could suit my use case. I've implemented it, but rather than linking the accounts, it is creating additional accounts. Here is what my implementation looks like:

PACKAGES ADDED:
meteor add accounts-facebook
meteor add accounts-twitter
meteor add bozhao:link-accounts
meteor add service-configuration

    
    <template name="signInTmpl">
          <button class="btn btn-facebook">Sign in with Facebook</button>  
    </template>

    
    <template name="linkTweetsTmpl">
          <button class="btn btn-twitter">Connect Twitter Account</button>
    </template>

    //client/linkTweets.js
    Template.linkTweetsTmpl.events({
          'click .btn-twitter': function() {
          Meteor.linkWithTwitter(function(err) {
          //Do if conditional ... 
          }) 
      }
    })

    //server/accounts.js
    var createServiceConfiguration;

    createServiceConfiguration = function(service, clientId, secret) {
     var config;
     ServiceConfiguration.configurations.remove({
      service: service
      });
     config = {
      generic: {
       service: service,
       clientId: clientId,
       secret: secret
     },
    instagram: {
      service: service,
      clientId: clientId,
      scope: 'basic',
      secret: secret,
      loginStyle: "redirect"
    },
    facebook: {
      service: service,
      appId: clientId,
      secret: secret,
      loginStyle: "redirect"
    },
    twitter: {
      service: service,
      consumerKey: clientId,
      secret: secret,
      loginStyle: "redirect"
    }
    };
     switch (service) {
      case 'instagram':
        return ServiceConfiguration.configurations.insert(config.instagram);
      case 'facebook':
        return ServiceConfiguration.configurations.insert(config.facebook);
      case 'twitter':
        return ServiceConfiguration.configurations.insert(config.twitter);
      default:
        return ServiceConfiguration.configurations.insert(config.generic);
      }
    };
    //DEV KEYS
    createServiceConfiguration('instagram', 'api-key', 'api-secret')
    createServiceConfiguration('facebook', 'api-key', 'api-secret')
    createServiceConfiguration('twitter', 'api-key', 'api-secret')
    createServiceConfiguration('google', 'api-key', 'api-secret')

I can successfully sign in with Facebook and when I click on the "Connect Twitter Button" it goes through the authorisation sequence fine, but then creates another account altogether.

Any thoughts on where I am going wrong or have I misunderstood the package?

**Comment by yubozhao** [comment]
@phinmpofu did you solve it?
