### ISSUE TITLE
Add loginOrLinkWith

### ISSUE THREAD

**Issue by lorensr** [yubozhao/meteor-link-accounts#2]
Feature Request: If a user is given a number of login service options, and doesn't remember which they used before, and they use a wrong one that has the same email, it would be nice if the accounts were linked.

**Comment by CookPete** [comment]
I think what @lorensr is trying to explain is that a user cannot log in with an account they have linked. For example:

* Log in with Facebook
* Use `Meteor.linkWithTwitter` to link account to Twitter
* Log out
* Log in with Twitter

I think in an ideal world, it would log you in to your original linked up account. What actually happens, however, is a new account is created, with Twitter as the "base" account. I don't know if this warrants re-opening this issue, but it certainly is a desirable feature.

**Comment by yubozhao** [comment]
Hi @CookPete 

This package is already designed that you could login with either accounts you linked/registered.   There is no concept of base account.

**Comment by lorensr** [comment]
I meant that if you eg create an accounts-password account with email X and
later on try to login with Facebook instead, and your FB account also uses
email X, it would be good if you could merge the two accounts.

**Comment by yubozhao** [comment]
@lorensr 
Sorry I didn't see your comment until today.   The use case you mentioned would be pretty useful.   I don't want this package step oout its boundary, which is just link account to current user.    I want app developer has flexibility to choose.

But I will consider making an account extension package that is the end all solution for all account needs

**Comment by lorensr** [comment]
I see, thanks!

**Comment by lorensr** [comment]
The second smaller answer here on SO looks good:

http://stackoverflow.com/a/28015727/627729

**Comment by lorensr** [comment]
Oh! I found a package for this:

https://github.com/splendido/meteor-accounts-meld
