### ISSUE TITLE
problem linking to GitHub

### ISSUE THREAD

**Issue by philcruz** [yubozhao/meteor-link-accounts#20]
My app allows login with Google, GitHub and Twitter. That works fine. I added this package to allow linking an existing account with other accounts. Google works fine. When I call

     Meteor.linkWithGithub();

I get

    Uncaught TypeError: Cannot read property 'redirectUrl' of undefinedGithub.requestCredential @     github_client.js:33

Is there some configuration required for GitHub? What could be the problem?

**Comment by philcruz** [comment]
And I get the some error with Twitter.

**Comment by philcruz** [comment]
This did the trick

    Meteor.linkWithGithub({"redirectUrl": "http://localhost:3000"});

Would be good to document that.

**Comment by yubozhao** [comment]
hi @philcruz   I will document this.  sorry about it

**Comment by joseconstela** [comment]
where are the docs?
