### ISSUE TITLE
Propagate server error to client

### ISSUE THREAD

**Issue by achtan** [yubozhao/meteor-link-accounts#22]
hi, on server i got message `Exception while invoking method 'login' MongoError: E11000 duplicate key error index: meteor.users.$services.twitter.id_1  dup key: { : "3822176249" }` BUT in client i see only `"Internal server error [500]"` so i can't tell user that his twitter account is already connected to other user account...

can you pls propagate mongo server error to the client?

**Comment by yubozhao** [comment]
@achtan I see your issue.   Right now I am piggyback on Meteor's existing account system... I am not too sure it is possible without study the code, I will work on this and find a good solution.

I know this issue would be important.

**Comment by achtan** [comment]
Or you can chceck if new account is already in DB before you try to merge it. And if it is, you will throw your own exception or so...

**Comment by acemtp** [comment]
Okay, I have the same error (I use your lib since months without issue). It's clearly a problem related to the meteor 1.2.

`{ : "3822176249" }` the key is empty, but should be `id`.

really strange and completely blocking for me. If you have an idea, i'll be happy

**Comment by yubozhao** [comment]
@acemtp I will check it out later on today.

**Comment by acemtp** [comment]
ok i found that the problem of duplicate is because the twitter id is already used by another account.

I'm almost sure that there a really strange bug that occurs randomly that link a twitter account to the bad meteor user account.

**Comment by yubozhao** [comment]
check out ef05988c5fcbc737f16580b8eb015f284272d51f

**Comment by acemtp** [comment]
Thanks @yubozhao for the quick fix, at least the error will be easier to understand :)

**Comment by yubozhao** [comment]
Cool. Going to close the issue now. Feel free to reopen it.
