### ISSUE TITLE
How to forbid user to create account when login with 3rd party services?

### ISSUE THREAD

**Issue by zhaoyao91** [yubozhao/meteor-link-accounts#25]
Thanks, with this great package, we can link services with existing accounts easily.
But, the user may also login with a not-linked service, which cause creating new account, which is not expected.
What's the good enough way to handle this situation?

**Comment by yubozhao** [comment]
hey @zhaoyao91 I am not fully understand the problem, could you explain a little bit more?

Thank you for your support!

**Comment by zhaoyao91** [comment]
By the time I post this question, the situation is: user can link an account with a service, and then, login with the service. But if the service is not linked with any account,  the action of 'login with service' will create an account without email, username or even password, which is not expected.

So I want a solution to allow the user to login with a linked service, but forbid them to create an account with a service.

**Comment by yubozhao** [comment]
What version of this package are you using?

As of now, I let the application developer decided what to do with that.   As you can see here  https://github.com/yubozhao/meteor-link-accounts/blob/master/core-services/meetup.js#L5

I would suggest to do a check for user before hand, also this could be easily handled by UI.

**Comment by yubozhao** [comment]
let me know if you run into this, i will open this issue again
