### ISSUE TITLE
"LinkedIn is not defined" error when calling Meteor.loginWithLinkedin

### ISSUE THREAD

**Issue by evilandfox** [yubozhao/meteor-link-accounts#26]
Hi.
Maybe that is my failure.
`jonperl:accounts-linkedin` package is installed.

**Comment by yubozhao** [comment]
Ok. I am on a vacation. Going to check out it once I get back(next week ish)

**Comment by evilandfox** [comment]
ok, thanks)

**Comment by yubozhao** [comment]
Going to keep it open until I fix this bug. ;)

**Comment by evilandfox** [comment]
Sorry, I clicked on "Close this comment" )) I am beginner on GitHub ))

**Comment by yubozhao** [comment]
No worries. :)

**Comment by yubozhao** [comment]
@evilandfox Sorry for the late update, but it is solved in 1.1.15 version, let me know if there is any issue.

**Comment by evilandfox** [comment]
Thanks, great :+1:
