### ISSUE TITLE
Security issue with _accounts/unlink/service method

### ISSUE THREAD

**Issue by dburles** [yubozhao/meteor-link-accounts#27]
Hey @yubozhao there's a security issue surrounding this method https://github.com/yubozhao/meteor-link-accounts/blob/master/link_accounts_server.js#L100-L105 as it makes it possible for anyone to unlink a service of any user.

**Comment by dburles** [comment]
This function also calls the method with the arguments in the wrong order: https://github.com/yubozhao/meteor-link-accounts/blob/master/link_accounts_client.js#L30-L33 (also this line is redundant https://github.com/yubozhao/meteor-link-accounts/blob/master/link_accounts_client.js#L31)

**Comment by dburles** [comment]
Just one other question (not related), I think it might make sense to remove the `id` field from the service data as that will then allow the same service to be linked to multiple user accounts. Thanks :)

**Comment by yubozhao** [comment]
@dburles Thanks man!  Going to check them out and will fix them.  I felt pretty excited about you using this! Have been following you for a while...

**Comment by yubozhao** [comment]
@dburles on the second question.  I thought about that at beginning of this package. I don't want to make it too complicated. Also, I think that use case requires a lot of special care.  It might be too much for this package.

Now you mentioned it, I might try to figure out how to put that into here, if that is the right choice.

**Comment by dburles** [comment]
Cool! no problem! Yeah you're right, it's tricky – I'll have a think about it a bit more though I think what you have is a reasonable default (your comment on making it configurable may be an idea).

Removing the ID allows any number of accounts to link to the same service, but the tradeoff is that you cannot sign in using that service. In the meantime I've [forked the package here](https://github.com/versolearning/meteor-link-accounts).

**Comment by yubozhao** [comment]
@dburles Just pushed fix for the issue, it turns out, I left testing code in there.  :(

Still thinking about how to handle multiply accounts for same services....

**Comment by edemaine** [comment]
The testing code (Meteor method `_accounts/unlink/service`) you removed, or something similar, needs to be put in the sample application, for the sample application to support unlinking...

**Comment by yubozhao** [comment]
@edemaine sorry for the delay....but it is fixed in the 1.2 version

**Comment by MichaelJCole** [comment]
@yubozhao I see the code in the repo changed, but it doesn't look like the [atmosphere package](https://atmospherejs.com/bozhao/link-accounts) was updated

**Comment by yubozhao** [comment]
@MichaelJCole solved  thanks for the heads up
