### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by trevorbass** [yubozhao/meteor-link-accounts#28]
To allow interpretation on the client, errors on the server should be thrown using "throw new Meteor.Error(...)" rather than "throw new Error(...)".

With errors currently thrown using "throw new Error(...)", the following client-side call will result in a generic internal server error, no matter what the error is:
    Meteor.linkWithTwitter( function(error) {
      console.log(error)
    });

I'd also suggest including some standardized error codes so that developers can write their own error text on the client side.

(Otherwise, this is a great tool - very useful!)

**Comment by yubozhao** [comment]
Hey @trevorbass 
thank you for the support!

I will update the error code and tight things up in the next release

**Comment by VioletaCalvo** [comment]
+1
Thank you for your package!

**Comment by yubozhao** [comment]
1.17 now servers meteor error, let me know how did it works for you guys
