### ISSUE TITLE
Multple users being created

### ISSUE THREAD

**Issue by aberios** [yubozhao/meteor-link-accounts#30]
I followed the example exactly using a brand new project and METEOR@1.2.1, and it appears if I first create an account using accounts-password and then try to link with accounts-github, a second user is created, and I am logged in with that user.  db.users.count() in mongo initially returns 1 user and then returns 2 users after I link with github.

It seems to work when using METEOR@1.1.0.2

**Comment by yubozhao** [comment]
hey @aberios I might need more info or reproducible code to see whats happening.

I tried with example code and It is working

**Comment by yubozhao** [comment]
any update on this @aberios ?  If not, I will close this issue until you runs into it again.
