### ISSUE TITLE
How about supporting weixin, qq, baidu ... and more China services?

### ISSUE THREAD

**Issue by zhaoyao91** [yubozhao/meteor-link-accounts#32]

**Comment by yubozhao** [comment]
If you have existing accounts login package for those services. I would gladly to add them into this package.

But I probably dont have enough free time to develop account package for them then add them myself

**Comment by yubozhao** [comment]
Add support for qq and wechat thanks to @leonzhang1109

**Comment by zhaoyao91** [comment]
great, thanks @yubozhao , @leonzhang1109
