### ISSUE TITLE
error when link with a service account which is already linked with other user

### ISSUE THREAD

**Issue by zhaoyao91** [yubozhao/meteor-link-accounts#33]
if an service accounts is already linked with some other user, call linkWith <service> will cause 500 error,which is bad because client can't handle it well.

could you fix this, or, even better, offer some way to config the strategies of allow/disallow link/unlink with service?

**Comment by zhaoyao91** [comment]
this is a compatibility problem with beta version of meteor 1.3

**Comment by yubozhao** [comment]
Package was not designed to have a config to allow/disallow link/unlink with existing service account.

I think you could put into try / catch to solve this issue and display error on the client side.

I will look into it this week, since it is going to be holiday soon.

**Comment by yubozhao** [comment]
It is now fixed in 1.17.  It will throw Meteor error, you should able to handle that.

**Comment by zhaoyao91** [comment]
thanks.
