### ISSUE TITLE
error when calling  Accounts.unlinkService on server side

### ISSUE THREAD

**Issue by zhaoyao91** [yubozhao/meteor-link-accounts#34]
I20151215-16:21:57.675(8)? Exception while invoking method 'AccountsEx.methods.unlinkService' ReferenceError: Mongo is not defined
I20151215-16:21:57.675(8)?     at AccountsServer.Accounts.unlinkService (packages/bozhao_link-accounts/link_accounts_server.js:78:1)
I20151215-16:21:57.675(8)?     at [object Object].methods.unlinkService.ValidatedMethod.run (packages/accounts-ex/server/methods.js:467:22)
I20151215-16:21:57.675(8)?     at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:82:43)
I20151215-16:21:57.675(8)?     at [object Object].ValidatedMethod.connection.methods._connection$methods.(anonymous function) (packages/mdg:validated-method/validated-method.js:32:23)
I20151215-16:21:57.675(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1698:12)
I20151215-16:21:57.675(8)?     at packages/ddp-server/livedata_server.js:708:19
I20151215-16:21:57.675(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151215-16:21:57.675(8)?     at packages/ddp-server/livedata_server.js:706:40
I20151215-16:21:57.675(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151215-16:21:57.675(8)?     at packages/ddp-server/livedata_server.js:704:46

**Comment by zhaoyao91** [comment]
this is a compatibility problem with meteor 1.3 beta.

**Comment by yubozhao** [comment]
ok, I will look into it.

**Comment by yubozhao** [comment]
did you add mongo package??

**Comment by zhaoyao91** [comment]
no, I didn't add mongo in my app, but I think a package should take care of its own dependencies. no problem, meteor 1.3 is not stable yet, this may be fixed in the future.

**Comment by yubozhao** [comment]
@zhaoyao91 You need add mongo  for your project, as of 1.2 Meteor does not include mongo automatically.  This actually break core package as well.

**Comment by zhaoyao91** [comment]
thanks, I will be careful about this.
