### ISSUE TITLE
Spotify not linking

### ISSUE THREAD

**Issue by sadiklsd** [yubozhao/meteor-link-accounts#43]
in chrome console:
Uncaught Error: Please include xinranxiao:meteor-spotify package [403]

on terminal:
meteor add  xinranxiao:meteor-spotify 
 => Errors while parsing arguments:                                 
While adding package xinranxiao:meteor-spotify:
error: no such package

However if you change in community-services/spotify.js
the line
    if (!Package['xinranxiao:meteor-spotify'] || !Package['xinranxiao:accounts-spotify'] ) {
by 
    if (!Package['xinranxiao:spotify'] || !Package['xinranxiao:accounts-spotify'] ) {

then it works

Could you push the change or do you prefer a pull request?

**Comment by yubozhao** [comment]
Ok, will do

**Comment by yubozhao** [comment]
done
