### ISSUE TITLE
linkWithInstagram asks to install wechat package

### ISSUE THREAD

**Issue by chemuto** [yubozhao/meteor-link-accounts#48]
I believe there is a bug in this file: https://github.com/yubozhao/meteor-link-accounts/blob/9b120954af79280a3cd7658d0e850ad90a53c8b8/community-services/wechat.js

I am trying to use linkWithInstagram and it keeps asking to install leonzhang1109:accounts-wechat package

Thanks

**Comment by yubozhao** [comment]
oh yeah, oops. will change it now

**Comment by yubozhao** [comment]
@chemuto please update to 1.2.8 to get the fixed version.
