### ISSUE TITLE
Using this with Meteor 1.3?

### ISSUE THREAD

**Issue by dfischer** [yubozhao/meteor-link-accounts#51]
Seems like it doesn't have access to other libraries so it blows up...

`Uncaught ReferenceError: Slack is not defined`

----

Going to try a PR...

----

Tried to do something like this

```
import {
  Slack
} from 'meteor/acemtp:accounts-slack';
```

But import is an unexpected token within a package... damn.

**Comment by shacks** [comment]
Any updates bud?

**Comment by dfischer** [comment]
Yeah, I forked acemtp:accounts-slack and added api.export('Slack') to the package.js - I did some other tweaks as well to return more data in the profile object so you may not want to use my fork.

`https://github.com/dfischer/meteor-accounts-slack/` `meteor add dfischer:accounts-slack`

**Comment by shacks** [comment]
Thank You, That works like a charm !!!

**Comment by yubozhao** [comment]
Thanks @dfischer WIll close this for now
