### ISSUE TITLE
How do I configure, Meteor.linkWithFacebook, to request more data (friends list) from a user's facebook account?

### ISSUE THREAD

**Issue by robskrob** [yubozhao/meteor-link-accounts#54]
Meteor.linkWithFacebook, will only prompt the user to provide his/her standard/required info and email. I would like to give the use the option to provide my app access to the user's friend's list. I've tried passing arguments to the method, Meteor.linkWithFacebook(['user_friends', 'user_location', 'user_events', 'friends_events', 'friends_location', 'friends_about_me', 'user_status', 'friends_status', 'read_friendlists']), but it still does not seem to request permission to have more than just access to an email.

Are there options that I can pass to, Meteor.linkWithFacebook, which will allow it to access the user for more of its data?

**Comment by kafechew** [comment]
@robskrob I'm looking a solution for this too. Did you solve this extra Facebook permissions issue?

**Comment by yubozhao** [comment]
let me triage it and get back to you guys

**Comment by robskrob** [comment]
@kafechew the following worked for me:
`Meteor.linkWithFacebook({requestPermissions: ['user_friends', 'email']}, (err, resp)=> {...`

**Comment by kafechew** [comment]
@robskrob Thanks~ Best solution! :-)
