### ISSUE TITLE
FB Permission issues

### ISSUE THREAD

**Issue by shadowzick** [yubozhao/meteor-link-accounts#57]
Hello, I'm trying to add these specific permissions 

`[
    "public_profile",
    "user_friends",
        "email",
        "user_about_me",
        "user_actions.books",
        "user_actions.fitness",
        "user_actions.music",
        "user_actions.news",
        "user_actions.video",
        "user_birthday",
        "user_education_history",
        "user_events",
        "user_games_activity",
        "user_hometown",
        "user_likes",
        "user_location",
        "user_managed_groups",
        "user_photos",
        "user_posts",
        "user_relationships",
        "user_relationship_details",
        "user_religion_politics",
        "user_tagged_places",
        "user_videos",
        "user_website",
        "user_work_history",
        "read_custom_friendlists",
        "read_insights",
        "read_audience_network_insights",
        "read_page_mailboxes",
        "manage_pages",
        "publish_pages",
        "publish_actions",
        "rsvp_event",
        "pages_show_list",
        "pages_manage_cta",
        "pages_manage_instant_articles",
        "ads_read",
        "ads_management",
        "pages_messaging",
        "pages_messaging_phone_number"
      ]`

so I tried 
`Meteor.linkWithFacebook({requestPermissions: Meteor.settings["public"]["FacebookApp"].permission}, function (err,res) {
                    if(!err){
                        console.log("Facebook Account Connected!");
                    } else {
                        console.log("Error: ", err);
                    }
                });`

but the only permission that's showing up is the public profile, friend list and email address alone.
Please help. thanks

**Comment by StorytellerCZ** [comment]
Also quiet a few of them have been recently removed or renamed. Many require app review from Facebook. Also Meteor is only going to retrieve details limited to the user, any additional stuff depends on your own code.
