### ISSUE TITLE
Can't use accounts-facebook and facebook package together

### ISSUE THREAD

**Issue by michaelcbrook** [yubozhao/meteor-link-accounts#63]
When trying to call Meteor.linkWithFacebook, I get an uncaught error saying

> Please include accounts-facebook and facebook package or cordova-fb package [403]

But including both the accounts-facebook and facebook packages results in a crash of the Meteor app, with Meteor saying

> Error: Already registered the facebook OAuth service
at Object.OAuth.registerService (packages/oauth.js:65:11)
at packages/facebook-oauth.js:49:7
at packages/facebook-oauth.js:125:4
at packages/facebook-oauth.js:137:3

Maybe this line in `bozhao_link-accounts/core-services/facebook.js`

`      if(!Package['accounts-facebook'] || !Package['facebook']) {
        throw new Meteor.Error(403, 'Please include accounts-facebook and facebook package or cordova-fb package')
      }
`

should insead be

`      if(!Package['accounts-facebook'] && !Package['facebook']) {
        throw new Meteor.Error(403, 'Please include accounts-facebook and facebook package or cordova-fb package')
      }
`

?

Right now, I have no way to call Meteor.linkWithFacebook()

**Comment by ZubMono** [comment]
I'm having the same issue, cannot link to Facebook and Google. Unlink is working btw,

**Comment by danielparas** [comment]
Encountering this issue also

**Comment by ingleo** [comment]
This error appears because you're trying to use two different versions, the "facebook" package was deprecated and replaced with "accounts-facebook", it has a dependant package that is "facebook-oauth" (this one create the conflict ), according to the meteor version that you're using, is necesary to remove "facebook" package, in this way, the file oauth.js is generated by the "facebook-oauth" package.

I hope help you, regards

**Comment by ingleo** [comment]
There are a conflict in the source code in this part too, between the package "btafel:accounts-facebook-cordova" and "accounts-facebook", every one register the "facebook" service, here:

```javascript
if (Meteor.isCordova) {
      if (!Package['btafel:accounts-facebook-cordova']) {
        throw new Meteor.Error(403, 'Please include btafel:accounts-facebook-cordova package or cordova-fb package')
      }
    } else {
      if (!Package['accounts-facebook'] || !facebookPackage) {
        throw new Meteor.Error(403, 'Please include accounts-facebook and facebook-oauth package or cordova-fb package')
      }
    }
```

**Comment by StorytellerCZ** [comment]
Is this still an issue? Looking at the code it looks like it should be fixed now.
