### ISSUE TITLE
Is it compatible with okland/accounts-phone?

### ISSUE THREAD

**Issue by darkbasic** [yubozhao/meteor-link-accounts#66]
My app is going to use whatsapp-style authentication (okland/accounts-phone) and Facebook authentication (accounts-facebook). Is it possible to link both with meteor-link-accounts?

**Comment by StorytellerCZ** [comment]
`accounts-facebook` is included in this packages. `okland:accounts-phone` is not, but unless there is a major difference on how `okland:accounts-phone` manages authentication it should be simple to add it (just ask the creators or follow example from other services).
