### ISSUE TITLE
 linkedIn support?

### ISSUE THREAD

**Issue by sasikanth513** [yubozhao/meteor-link-accounts#7]
as in the title are you planning for linkedin?

**Comment by yubozhao** [comment]
hi @meenie 

Thank you for the linkedin package.  I will work on it for the next release

**Comment by dukye** [comment]
+1 would like to have this connector :)

Thx in advance 
duke

**Comment by caio-ribeiro-pereira** [comment]
+1 Me too!

**Comment by yubozhao** [comment]
check out the new version.  Close it for now, if have question/issue, please open a new one
